ALTER TABLE "damage_types" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "damage_types" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "spells" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "spells" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "mastery" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "mastery" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "weapon_properties" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "weapon_properties" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "weapon_to_weapon_properties" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "weapon_to_weapon_properties" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "weapons" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "weapons" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "encounters" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "encounters" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "characters" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "monsters" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "monsters" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "magic_items" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "magic_items" ALTER COLUMN "updated_at" SET NOT NULL;