volumes:
  db:

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: dnd_encounters
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5435:5432
    restart: on-failure:3
    volumes:
      - db:/var/lib/postgres/data
