apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deploy-jaeger
  labels:
    app: chat-jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-jaeger
  template:
    metadata:
      labels:
        app: chat-jaeger
    spec:
      containers:
        - name: chat-jaeger
          image: jaegertracing/all-in-one:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 14250
            - containerPort: 14268
            - containerPort: 14269
            - containerPort: 9411
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: "9411"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          # volumeMounts:
          #   - name: data
          #     mountPath: /var/lib/postgresql/data
          # readinessProbe:
          #   exec:
          #     command:
          #     - /bin/sh
          #     - -c
          #     - -e
          #     - |
          #       exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          #       [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
          #   failureThreshold: 6
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 5
          # livenessProbe:
          #   exec:
          #     command:
          #     - /bin/sh
          #     - -c
          #     - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          #   failureThreshold: 6
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 5
      # volumes:
      #   - name: data
      #     persistentVolumeClaim:
      #       claimName: chat-pvc-postgres

---

apiVersion: v1
kind: Service
metadata:
  name: chat-svc-jaeger
  labels:
    app: chat-jaeger
spec:
  type: ClusterIP
  selector:
    app: chat-jaeger
  ports:
    - name: entry
      port: 5432
      targetPort: 5432
