/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardEncountersIndexRouteImport } from './routes/dashboard/encounters/index'
import { Route as DashboardCharactersIndexRouteImport } from './routes/dashboard/characters/index'
import { Route as DashboardCampaignsIndexRouteImport } from './routes/dashboard/campaigns/index'
import { Route as DashboardInviteInviteIdRouteImport } from './routes/dashboard/invite/$inviteId'
import { Route as DashboardEncountersEncounterIdRouteImport } from './routes/dashboard/encounters/$encounterId'
import { Route as DashboardCharactersCharacterIdRouteImport } from './routes/dashboard/characters/$characterId'
import { Route as DashboardCampaignsCampaignIdRouteImport } from './routes/dashboard/campaigns/$campaignId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEncountersIndexRoute =
  DashboardEncountersIndexRouteImport.update({
    id: '/encounters/',
    path: '/encounters/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCharactersIndexRoute =
  DashboardCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCampaignsIndexRoute = DashboardCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInviteInviteIdRoute = DashboardInviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEncountersEncounterIdRoute =
  DashboardEncountersEncounterIdRouteImport.update({
    id: '/encounters/$encounterId',
    path: '/encounters/$encounterId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCharactersCharacterIdRoute =
  DashboardCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCampaignsCampaignIdRoute =
  DashboardCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdRoute
  '/dashboard/characters/$characterId': typeof DashboardCharactersCharacterIdRoute
  '/dashboard/encounters/$encounterId': typeof DashboardEncountersEncounterIdRoute
  '/dashboard/invite/$inviteId': typeof DashboardInviteInviteIdRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/characters/': typeof DashboardCharactersIndexRoute
  '/dashboard/encounters/': typeof DashboardEncountersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdRoute
  '/dashboard/characters/$characterId': typeof DashboardCharactersCharacterIdRoute
  '/dashboard/encounters/$encounterId': typeof DashboardEncountersEncounterIdRoute
  '/dashboard/invite/$inviteId': typeof DashboardInviteInviteIdRoute
  '/dashboard/campaigns': typeof DashboardCampaignsIndexRoute
  '/dashboard/characters': typeof DashboardCharactersIndexRoute
  '/dashboard/encounters': typeof DashboardEncountersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdRoute
  '/dashboard/characters/$characterId': typeof DashboardCharactersCharacterIdRoute
  '/dashboard/encounters/$encounterId': typeof DashboardEncountersEncounterIdRoute
  '/dashboard/invite/$inviteId': typeof DashboardInviteInviteIdRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/characters/': typeof DashboardCharactersIndexRoute
  '/dashboard/encounters/': typeof DashboardEncountersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/dashboard/'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/characters/$characterId'
    | '/dashboard/encounters/$encounterId'
    | '/dashboard/invite/$inviteId'
    | '/dashboard/campaigns/'
    | '/dashboard/characters/'
    | '/dashboard/encounters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/dashboard'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/characters/$characterId'
    | '/dashboard/encounters/$encounterId'
    | '/dashboard/invite/$inviteId'
    | '/dashboard/campaigns'
    | '/dashboard/characters'
    | '/dashboard/encounters'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/$'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/dashboard/'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/characters/$characterId'
    | '/dashboard/encounters/$encounterId'
    | '/dashboard/invite/$inviteId'
    | '/dashboard/campaigns/'
    | '/dashboard/characters/'
    | '/dashboard/encounters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/encounters/': {
      id: '/dashboard/encounters/'
      path: '/encounters'
      fullPath: '/dashboard/encounters/'
      preLoaderRoute: typeof DashboardEncountersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/characters/': {
      id: '/dashboard/characters/'
      path: '/characters'
      fullPath: '/dashboard/characters/'
      preLoaderRoute: typeof DashboardCharactersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/campaigns/': {
      id: '/dashboard/campaigns/'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns/'
      preLoaderRoute: typeof DashboardCampaignsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invite/$inviteId': {
      id: '/dashboard/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/dashboard/invite/$inviteId'
      preLoaderRoute: typeof DashboardInviteInviteIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/encounters/$encounterId': {
      id: '/dashboard/encounters/$encounterId'
      path: '/encounters/$encounterId'
      fullPath: '/dashboard/encounters/$encounterId'
      preLoaderRoute: typeof DashboardEncountersEncounterIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/characters/$characterId': {
      id: '/dashboard/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/dashboard/characters/$characterId'
      preLoaderRoute: typeof DashboardCharactersCharacterIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/campaigns/$campaignId': {
      id: '/dashboard/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/dashboard/campaigns/$campaignId'
      preLoaderRoute: typeof DashboardCampaignsCampaignIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCampaignsCampaignIdRoute: typeof DashboardCampaignsCampaignIdRoute
  DashboardCharactersCharacterIdRoute: typeof DashboardCharactersCharacterIdRoute
  DashboardEncountersEncounterIdRoute: typeof DashboardEncountersEncounterIdRoute
  DashboardInviteInviteIdRoute: typeof DashboardInviteInviteIdRoute
  DashboardCampaignsIndexRoute: typeof DashboardCampaignsIndexRoute
  DashboardCharactersIndexRoute: typeof DashboardCharactersIndexRoute
  DashboardEncountersIndexRoute: typeof DashboardEncountersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCampaignsCampaignIdRoute: DashboardCampaignsCampaignIdRoute,
  DashboardCharactersCharacterIdRoute: DashboardCharactersCharacterIdRoute,
  DashboardEncountersEncounterIdRoute: DashboardEncountersEncounterIdRoute,
  DashboardInviteInviteIdRoute: DashboardInviteInviteIdRoute,
  DashboardCampaignsIndexRoute: DashboardCampaignsIndexRoute,
  DashboardCharactersIndexRoute: DashboardCharactersIndexRoute,
  DashboardEncountersIndexRoute: DashboardEncountersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
