/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EncounterRouteImport } from './routes/encounter'
import { Route as CreateProfileRouteImport } from './routes/createProfile'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as EncounterEncounterIdRouteImport } from './routes/encounter/$encounterId'
import { Route as CharactersCharacterIdRouteImport } from './routes/characters/$characterId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EncounterRoute = EncounterRouteImport.update({
  id: '/encounter',
  path: '/encounter',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateProfileRoute = CreateProfileRouteImport.update({
  id: '/createProfile',
  path: '/createProfile',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CharactersRoute,
} as any)
const EncounterEncounterIdRoute = EncounterEncounterIdRouteImport.update({
  id: '/$encounterId',
  path: '/$encounterId',
  getParentRoute: () => EncounterRoute,
} as any)
const CharactersCharacterIdRoute = CharactersCharacterIdRouteImport.update({
  id: '/$characterId',
  path: '/$characterId',
  getParentRoute: () => CharactersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/createProfile': typeof CreateProfileRoute
  '/encounter': typeof EncounterRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/encounter/$encounterId': typeof EncounterEncounterIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createProfile': typeof CreateProfileRoute
  '/encounter': typeof EncounterRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/encounter/$encounterId': typeof EncounterEncounterIdRoute
  '/characters': typeof CharactersIndexRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters': typeof CharactersRouteWithChildren
  '/createProfile': typeof CreateProfileRoute
  '/encounter': typeof EncounterRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/encounter/$encounterId': typeof EncounterEncounterIdRoute
  '/characters/': typeof CharactersIndexRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters'
    | '/createProfile'
    | '/encounter'
    | '/home'
    | '/login'
    | '/logout'
    | '/characters/$characterId'
    | '/encounter/$encounterId'
    | '/characters/'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/createProfile'
    | '/encounter'
    | '/login'
    | '/logout'
    | '/characters/$characterId'
    | '/encounter/$encounterId'
    | '/characters'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/createProfile'
    | '/encounter'
    | '/home'
    | '/login'
    | '/logout'
    | '/characters/$characterId'
    | '/encounter/$encounterId'
    | '/characters/'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRouteWithChildren
  CreateProfileRoute: typeof CreateProfileRoute
  EncounterRoute: typeof EncounterRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encounter': {
      id: '/encounter'
      path: '/encounter'
      fullPath: '/encounter'
      preLoaderRoute: typeof EncounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createProfile': {
      id: '/createProfile'
      path: '/createProfile'
      fullPath: '/createProfile'
      preLoaderRoute: typeof CreateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/characters/': {
      id: '/characters/'
      path: '/'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/encounter/$encounterId': {
      id: '/encounter/$encounterId'
      path: '/$encounterId'
      fullPath: '/encounter/$encounterId'
      preLoaderRoute: typeof EncounterEncounterIdRouteImport
      parentRoute: typeof EncounterRoute
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdRouteImport
      parentRoute: typeof CharactersRoute
    }
  }
}

interface CharactersRouteChildren {
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersCharacterIdRoute: CharactersCharacterIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface EncounterRouteChildren {
  EncounterEncounterIdRoute: typeof EncounterEncounterIdRoute
}

const EncounterRouteChildren: EncounterRouteChildren = {
  EncounterEncounterIdRoute: EncounterEncounterIdRoute,
}

const EncounterRouteWithChildren = EncounterRoute._addFileChildren(
  EncounterRouteChildren,
)

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRouteWithChildren,
  CreateProfileRoute: CreateProfileRoute,
  EncounterRoute: EncounterRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
